### ISSUE TITLE
Moi Mikko! :D

### ISSUE THREAD

**Issue by gustafla** [kumikumi/sudoku#1]
En keksinyt muuta tapaa ottaa yhteyttä koska lopetin Facebookin käytön. Olisi ihan kiva taas chattailla. Olen Telegramissa nimellä gustafla, sekä emailiakin voi lähettää osoitteeseen luutifa ät jkry piste org. Keksitään jokin parempi kommunikaatiokeino kuin Github Issues :D

Terveisin Lauri (peliohjelmointileirien apulainen)

**Comment by kumikumi** [comment]
Mahtava kommunikaatiokanava! :D Lisään telegramissa
